directories: 
  Healthy: "/Users/gyongyosilab/Desktop/Test_metilene/Healthy"
  Cardio_LC: "/Users/gyongyosilab/Desktop/Test_metilene/Cardio_LC"
  Pulmo_LC: "/Users/gyongyosilab/Desktop/Test_metilene/Pulmo_LC"

samples: 
  Healthy:
    - "DE07NGSLABD100887_CpG_noXY.bedGraph"
    - "DE16NGSLABD100822_CpG_noXY.bedGraph"
    - "DE24NGSLABD100872_CpG_noXY.bedGraph"
    - "DE28NGSLABD100897_CpG_noXY.bedGraph"
    - "DE37NGSLABD100832_CpG_noXY.bedGraph"
    - "DE45NGSLABD100882_CpG_noXY.bedGraph"
    - "DE96NGSLABD100837_CpG_noXY.bedGraph"
    - "DE87NGSLABD100902_CpG_noXY.bedGraph"
    - "DE83NGSLABD100877_CpG_noXY.bedGraph"
    - "DE75NGSLABD100827_CpG_noXY.bedGraph"
    - "DE66NGSLABD100892_CpG_noXY.bedGraph"
    - "DE49NGSLABD100907_CpG_noXY.bedGraph"
  Cardio_LC:
    - "DE02NGSLABD100880_CpG_noXY.bedGraph"
    - "DE61NGSLABD100885_CpG_noXY.bedGraph"
    - "DE23NGSLABD100890_CpG_noXY.bedGraph"
    - "DE65NGSLABD100910_CpG_noXY.bedGraph"
    - "DE32NGSLABD100825_CpG_noXY.bedGraph"
    - "DE78NGSLABD100870_CpG_noXY.bedGraph"
    - "DE40NGSLABD100875_CpG_noXY.bedGraph"
    - "DE82NGSLABD100895_CpG_noXY.bedGraph"
    - "DE44NGSLABD100900_CpG_noXY.bedGraph"
    - "DE91NGSLABD100830_CpG_noXY.bedGraph"
    - "DE53NGSLABD100835_CpG_noXY.bedGraph"
  Pulmo_LC:
    - "DE05NGSLABD100826_CpG_noXY.bedGraph"
    - "DE51NGSLABD100871_CpG_noXY.bedGraph"
    - "DE13NGSLABD100876_CpG_noXY.bedGraph"
    - "DE55NGSLABD100896_CpG_noXY.bedGraph"
    - "DE17NGSLABD100901_CpG_noXY.bedGraph"
    - "DE64NGSLABD100831_CpG_noXY.bedGraph"
    - "DE26NGSLABD100836_CpG_noXY.bedGraph"
    - "DE72NGSLABD100881_CpG_noXY.bedGraph"
    - "DE34NGSLABD100886_CpG_noXY.bedGraph"
    - "DE76NGSLABD100906_CpG_noXY.bedGraph"
    - "DE38NGSLABD100911_CpG_noXY.bedGraph"
    - "DE93NGSLABD100891_CpG_noXY.bedGraph"
